spring.application.name=link-snap
spring.datasource.url=jdbc:mysql://localhost:3306/linksnap
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update

jwt.secret=617ceb47688fe59627335e32a1de8c3a5d65be4ff83fa720c7c6024579cae329
jwt.expiration=172800000